version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

jobs:
  security-scans:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-iac
          filters:
            branches:
              ignore: main

      - security-scans:
          name: Security Scans
          context:
            - analysis-iac
